### ISSUE TITLE
Please make sure you have the correct access rights

### ISSUE THREAD

**Issue by nooranalytics** [likerRr/code4goal-resume-parser#5]
Hi, your project seems interesting and i'd like to give it a try.  I am trying to clone the repository but I keep getting : 

Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights

**Comment by likerRr** [comment]
Seems like the error doesn't relate to the project. It seems like your terminal (or a tool which you use for cloning) doesn't see your git public key. Please refer to [github documentation](https://help.github.com/articles/connecting-to-github-with-ssh/) or try to clone the repo via https: 
`git clone https://github.com/likerRr/code4goal-resume-parser.git`
